import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import NextAuthSessionProvider from "./provider";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <NextAuthSessionProvider>
          <Navbar></Navbar>
          {children}
          <Toaster position="top-right" />
        </NextAuthSessionProvider>

          {/* <main className="flex-1 ">{children}</main> */}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
